version: '3'
services:
  database:
    container_name: database
    image: mysql:5.7
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: business_flow
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
