// Code generated by validator, DO NOT EDIT

import { TaskRule } from '../base';

export const task1 = new TaskRule({
  name: 'トリガ',
  id: 1,
  from: {
    allowTasks: [],
    allowPaths: [],
    denyTasks: [
      'トリガ',
      '入出力',
      'システムからの入力',
      'システムからの出力',
      '処理',
      'データストア',
    ],
    denyPaths: ['遷移', '通信'],
  },
  to: {
    allowTasks: ['入出力', 'システムからの入力', '処理'],
    allowPaths: ['遷移'],
    denyTasks: ['トリガ', 'システムからの出力', 'データストア'],
    denyPaths: ['通信'],
  },
});
