// Code generated by validator, DO NOT EDIT

import { TaskRule } from '../base';

export const task3 = new TaskRule({
  name: 'システムからの入力',
  id: 3,
  from: {
    allowTasks: [
      { name: 'トリガ', id: 1 },
      { name: '入出力', id: 2 },
      { name: 'システムからの入力', id: 3 },
      { name: 'システムからの出力', id: 4 },
      { name: 'データストア', id: 5 },
      { name: '処理', id: 6 },
      { name: '受領', id: 7 },
    ],
    allowPaths: [
      { name: '遷移', id: 1 },
      { name: '通信', id: 2 },
    ],
    denyTasks: [],
    denyPaths: [],
  },
  to: {
    allowTasks: [
      { name: 'トリガ', id: 1 },
      { name: '入出力', id: 2 },
      { name: 'システムからの入力', id: 3 },
      { name: 'システムからの出力', id: 4 },
      { name: 'データストア', id: 5 },
      { name: '処理', id: 6 },
    ],
    allowPaths: [{ name: '遷移', id: 1 }],
    denyTasks: [{ name: '受領', id: 7 }],
    denyPaths: [{ name: '通信', id: 2 }],
  },
});
