// Code generated by validator, DO NOT EDIT

import { TaskRule } from '../base';

export const task5 = new TaskRule({
  name: '処理',
  id: 5,
  from: {
    allowTasks: [
      'トリガ',
      '入出力',
      'システムからの入力',
      'システムからの出力',
      '処理',
      'データストア',
    ],
    allowPaths: ['遷移', '通信'],
    denyTasks: [],
    denyPaths: [],
  },
  to: {
    allowTasks: [
      'トリガ',
      '入出力',
      'システムからの入力',
      'システムからの出力',
      '処理',
      'データストア',
    ],
    allowPaths: ['遷移'],
    denyTasks: [],
    denyPaths: ['通信'],
  },
});
