// Code generated by validator, DO NOT EDIT

import { TaskRule } from '../base';

export const task1 = new TaskRule({
  name: 'トリガ',
  id: 1,
  from: {
    allowTasks: [],
    allowPaths: [],
    denyTasks: [
      { name: 'トリガ', id: 1 },
      { name: '入出力', id: 2 },
      { name: 'システムからの入力', id: 3 },
      { name: 'システムからの出力', id: 4 },
      { name: 'データストア', id: 5 },
      { name: '処理', id: 6 },
      { name: '受領', id: 7 },
    ],
    denyPaths: [
      { name: '遷移', id: 1 },
      { name: '通信', id: 2 },
    ],
  },
  to: {
    allowTasks: [
      { name: '入出力', id: 2 },
      { name: 'システムからの入力', id: 3 },
      { name: '処理', id: 6 },
    ],
    allowPaths: [{ name: '遷移', id: 1 }],
    denyTasks: [
      { name: 'トリガ', id: 1 },
      { name: 'システムからの出力', id: 4 },
      { name: 'データストア', id: 5 },
      { name: '受領', id: 7 },
    ],
    denyPaths: [{ name: '通信', id: 2 }],
  },
});
