// Code generated by validator, DO NOT EDIT

import { TaskRule } from '../base';

export const task6 = new TaskRule({
  name: 'データストア',
  id: 6,
  from: {
    allowTasks: [
      '入出力',
      'システムからの入力',
      'システムからの出力',
      '処理',
      'データストア',
    ],
    allowPaths: ['遷移', '通信'],
    denyTasks: ['トリガ'],
    denyPaths: [],
  },
  to: {
    allowTasks: [
      'トリガ',
      '入出力',
      'システムからの入力',
      'システムからの出力',
      '処理',
      'データストア',
    ],
    allowPaths: ['遷移', '通信'],
    denyTasks: [],
    denyPaths: [],
  },
});
