// Code generated by validator, DO NOT EDIT

import { PathRule } from '../base';

export const path2 = new PathRule({
  name: '通信',
  id: 2,
  from: {
    allowTasks: ['入出力', 'システムからの出力', 'データストア'],
    allowPaths: ['遷移', '通信'],
    denyTasks: ['トリガ', 'システムからの入力', '処理'],
    denyPaths: [],
  },
  to: {
    allowTasks: [
      'トリガ',
      '入出力',
      'システムからの入力',
      'システムからの出力',
      '処理',
      'データストア',
    ],
    allowPaths: ['遷移', '通信'],
    denyTasks: [],
    denyPaths: [],
  },
});
