// Code generated by validator, DO NOT EDIT

import { PathRule } from '../base';

export const path1 = new PathRule({
  name: '遷移',
  id: 1,
  from: {
    allowTasks: [
      'トリガ',
      '入出力',
      'システムからの入力',
      'システムからの出力',
      '処理',
      'データストア',
    ],
    allowPaths: ['遷移', '通信'],
    denyTasks: [],
    denyPaths: [],
  },
  to: {
    allowTasks: [
      'トリガ',
      '入出力',
      'システムからの入力',
      'システムからの出力',
      '処理',
      'データストア',
    ],
    allowPaths: ['遷移', '通信'],
    denyTasks: [],
    denyPaths: [],
  },
});
