// Code generated by validator, DO NOT EDIT

import { PathRule } from '../base';

export const path1 = new PathRule({
  name: '遷移',
  id: 1,
  from: {
    allowTasks: [
      { name: 'トリガ', id: 1 },
      { name: '入出力', id: 2 },
      { name: 'システムからの入力', id: 3 },
      { name: 'システムからの出力', id: 4 },
      { name: '処理', id: 5 },
      { name: 'データストア', id: 6 },
    ],
    allowPaths: [
      { name: '遷移', id: 1 },
      { name: '通信', id: 2 },
    ],
    denyTasks: [],
    denyPaths: [],
  },
  to: {
    allowTasks: [
      { name: 'トリガ', id: 1 },
      { name: '入出力', id: 2 },
      { name: 'システムからの入力', id: 3 },
      { name: 'システムからの出力', id: 4 },
      { name: '処理', id: 5 },
      { name: 'データストア', id: 6 },
    ],
    allowPaths: [
      { name: '遷移', id: 1 },
      { name: '通信', id: 2 },
    ],
    denyTasks: [],
    denyPaths: [],
  },
});
