name: reviewdog
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**/**.ts'
      - '**/**.tsx'
      - '.github/workflows/reviewdog.yml'

jobs:
  eslint:
    if: github.event.pull_request.draft == false
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - name: reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,tsx}'
      - name: eslint
        run: yarn lint
